<?php
/**
 * @category  Dinesh FrequentlyBought
 * @package   Dinesh_FrequentlyBought
 * @copyright Copyright (c) 2017 Dinesh
 * @author    Dinesh Team <support@dinesh.com>
 */
/* @var $block \Magento\Downloadable\Block\Catalog\Product\Links */ ?>
<?php $_linksPurchasedSeparately = $block->getLinksPurchasedSeparately(); ?>
<?php $productId = $block->getProduct()->getId(); ?>
<?php if ($block->getProduct()->isSaleable() && $block->hasLinks()):?>
    <?php $_links = $block->getLinks(); ?>
    <?php $_linksLength = 0; ?>
    <?php $_isRequired = $block->getLinkSelectionRequired(); ?>
    <div
    class="field downloads<?php if ($_isRequired) { echo ' required'; } ?>
    <?php if (!$_linksPurchasedSeparately) { echo ' downloads-no-separately'; } ?>">
        <label class="label"><span><?= $block->escapeHtml($block->getLinksTitle()) ?></span></label>
        <div
        class="control mg-fbt-options-list"
        id="mp-fbt-downloadable-links-list-<?= $block->escapeHtmlAttr($productId); ?>"
        data-mage-init='{"FbtPriceDownloadable":{
        "linkElement":"input:checkbox[value]",
        "allElements":"#mp_fbt_links_all_<?= $block->escapeHtmlAttr($productId); ?>",
        "config":<?= $block->escapeHtmlAttr($block->getJsonConfig()) ?>}}'
        data-container-for="downloadable-links">
            <?php foreach ($_links as $_link): ?>
                <?php $_linksLength++;?>
                <div class="field choice" data-role="link">
                    <?php if ($_linksPurchasedSeparately): ?>
                        <input
                        type="checkbox"
                        <?php if ($_isRequired): ?>data-validate="
                        {'validate-one-checkbox-required-by-name':'mp-fbt-downloadable-links-list-<?=
                        $block->escapeHtmlAttr($productId); ?>'}" <?php endif; ?>
                        name="links[<?= $block->escapeHtmlAttr($productId); ?>][]"
                        id="links_<?= $block->escapeHtmlAttr($productId); ?>_<?=
                        $block->escapeHtmlAttr($_link->getId()) ?>"
                        class="mp-fbt-multi-select"
                        value="<?= $block->escapeHtmlAttr($_link->getId()); ?>"
                        <?= $block->escapeHtmlAttr($block->getLinkCheckedValue($_link)); ?>/>
                    <?php endif; ?>
                    <label
                    class="label"
                    for="links_<?=
                    $block->escapeHtmlAttr($productId); ?>_<?= $block->escapeHtmlAttr($_link->getId()) ?>">
                        <span><?= $block->escapeHtml($_link->getTitle()); ?></span>
                        <?php if ($_link->getSampleFile() || $_link->getSampleUrl()): ?>
                            <a
                            class="sample link"
                            href="<?=
                            $block->escapeUrl($block->getLinkSampleUrl($_link)) ?>" <?=
                            $block->escapeHtmlAttr($block->getIsOpenInNewWindow() ? 'target="_blank"' : ''); ?>>
                                <?= $block->escapeHtml(__('sample')) ?>
                            </a>
                        <?php endif; ?>
                        <?php if ($_linksPurchasedSeparately): ?>
                            <?= /* @noEscape */ $block->getLinkPrice($_link); ?>
                        <?php endif; ?>
                    </label>
                </div>
            <?php endforeach; ?>
            <?php if ($_linksPurchasedSeparately && $_linksLength > 1): ?>
                <div class="field choice downloads-all">
                    <input type="checkbox"
                    data-notchecked="<?= $block->escapeHtml(__('Select all')) ?>"
                    data-checked="<?= $block->escapeHtml(__('Unselect all')) ?>"
                    id="mp_fbt_links_all_<?= $block->escapeHtmlAttr($productId); ?>" />
                    <label
                    class="label"
                    for="mp_fbt_links_all_<?= $block->escapeHtmlAttr($productId); ?>">
                        <span><?= $block->escapeHtml(__('Select all')) ?></span>
                    </label>
                </div>
            <?php endif; ?>
        </div>
        <?php if ($_isRequired): ?>
            <span id="links-advice-container"></span>
        <?php endif;?>
    </div>
<?php endif; ?>
