<?php
/**
 * @category  Dinesh FrequentlyBought
 * @package   Dinesh_FrequentlyBought
 * @copyright Copyright (c) 2017 Dinesh
 * @author    Dinesh Team <support@dinesh.com>
 */
$block->setPreconfiguredValue(); ?>
<?php $_product = $block->getProduct(); ?>
<?php $_associatedProducts = $block->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>

<div class="table-wrapper dinesh-fbt-grouped">
    <table
    class="table data grouped"
    id="dinesh-fbt-super-product-table-<?= $block->escapeHtmlAttr($_product->getId()); ?>">
        <caption class="table-caption"><?= $block->escapeHtml(__('Grouped product items')) ?></caption>
        <thead>
        <tr>
            <th class="col item" scope="col"><?= $block->escapeHtml(__('Product Name')) ?></th>
            <?php if ($_product->isSaleable()): ?>
                <th class="col qty" scope="col"><?= $block->escapeHtml(__('Qty')) ?></th>
            <?php endif; ?>
        </tr>
        </thead>

        <?php if ($_hasAssociatedProducts): ?>
            <?php foreach ($_associatedProducts as $_item): ?>
            <tbody>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('Product Name')); ?>" class="col item">
                        <strong class="product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong>
                        <?php if ($block->getCanShowProductPrice($_product)): ?>
                            <?php if ($block->getCanShowProductPrice($_item)): ?>
                                <?= /* @noEscape */ $block->getProductPrice($_item) ?>
                            <?php endif; ?>
                        <?php endif; ?>
                    </td>
                    <?php if ($_product->isSaleable()): ?>
                    <td data-th="<?= $block->escapeHtml(__('Qty')); ?>" class="col qty">
                        <?php if ($_item->isSaleable()): ?>
                            <div class="control qty">
                                <?php
                                $priceInfo = $_item->getPriceInfo()->getPrice('final_price')->getAmount()->getValue();
                                ?>
                                <input
                                type="number"
                                name="super_group[<?=
                                $block->escapeHtmlAttr($_product->getId()) ?>][<?=
                                $block->escapeHtmlAttr($_item->getId()) ?>]"
                                data-selector="super_group[<?=
                                $block->escapeHtmlAttr($_product->getId()) ?>][<?=
                                $block->escapeHtmlAttr($_item->getId()) ?>]"
                                maxlength="12"
                                value="<?= $block->escapeHtmlAttr($_item->getQty() * 1) ?>"
                                title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                                class="input-text qty dinesh-fbt-grouped-qty"
                                data-validate="{'validate-grouped-qty':'#dinesh-fbt-super-product-table-<?=
                                $block->escapeHtmlAttr($_product->getId()); ?>'}"
                                data-errors-message-box="#dinesh-fbt-validation-message-box-<?=
                                $block->escapeHtmlAttr($_product->getId()); ?>"
                                data-child-product-id="<?= $block->escapeHtmlAttr($_item->getId()) ?>"
                                data-child-product-price-amount="<?=
                                $block->escapeHtmlAttr($priceInfo); ?>"
                                data-child-product-price-total="0"/>
                            </div>
                        <?php else: ?>
                            <div class="stock unavailable" title="<?= $block->escapeHtml(__('Availability')) ?>">
                                <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                            </div>
                        <?php endif; ?>
                    </td>
                    <?php endif; ?>
                </tr>
                <?php if ($block->getCanShowProductPrice($_product)
                    && $block->getCanShowProductPrice($_item)
                    && trim($block->getProductPriceHtml(
                        $_item,
                        \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                    ))): ?>
                    <tr class="row-tier-price">
                        <td colspan="2">
                            <?= /* @noEscape */ $block->getProductPriceHtml(
                                $_item,
                                \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                            ) ?>
                        </td>
                    </tr>
                <?php endif; ?>
            </tbody>
            <?php endforeach; ?>
        <?php else: ?>
            <tbody>
                <tr>
                    <td class="unavailable"
                        colspan="<?php
                        if ($_product->isSaleable()):
                            ?>4<?php
                        else:
                            ?>3<?php
                        endif; ?>">
                        <?= $block->escapeHtml(__('No options of this product are available.')); ?>
                    </td>
                </tr>
            </tbody>
        <?php endif; ?>
    </table>
</div>
<div id="dinesh-fbt-validation-message-box-<?= $block->escapeHtmlAttr($_product->getId()); ?>"></div>
