<?php
/**
 * @category  Dinesh FrequentlyBought
 * @package   Dinesh_FrequentlyBought
 * @copyright Copyright (c) 2017 Dinesh
 * @author    Dinesh Team <support@dinesh.com>
 */
$product = $block->getProduct();
?>
<div class="swatch-opt" data-role="swatch-options-<?= $block->escapeHtmlAttr($product->getId()); ?>"></div>

<script type="text/x-magento-init">
    {
        "[data-role=swatch-options-<?= $block->escapeHtmlAttr($product->getId()); ?>]": {
            "FbtSwatchRenderer": {
                "jsonConfig": <?= /* @noEscape */ $block->getJsonConfig(); ?>,
                "jsonSwatchConfig": <?= /* @noEscape */ $block->getJsonSwatchConfig(); ?>
            }
        }
    }
</script>
