<?php
/**
 * @category  Dinesh FrequentlyBought
 * @package   Dinesh_FrequentlyBought
 * @copyright Copyright (c) 2017 Dinesh
 * @author    Dinesh Team <support@dinesh.com>
 */
$_option = $block->getOption() ?>
<?php $productId = $block->getProduct()->getId();?>
<?php $_selections = $_option->getSelections() ?>
<div
class="mg-fbt-field-option field option <?= $block->escapeHtmlAttr(($_option->getRequired()) ? ' required': ''); ?>"
id="mp-fbt-bundle-option-<?= $block->escapeHtmlAttr($productId); ?>-<?= $block->escapeHtmlAttr($_option->getId());?>"
data-price-amount="0">
    <label
    class="label"
    for="bundle-option-<?= $block->escapeHtmlAttr($productId); ?>-<?= $block->escapeHtmlAttr($_option->getId()) ?>">
        <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="control">
        <?php if ($block->showSingle()): ?>
            <?= /* @noEscape */ $block->getSelectionQtyTitlePrice($_selections[0]) ?>
            <input
            type="hidden"
            name="bundle_option[<?=
            $block->escapeHtmlAttr($productId); ?>][<?=
            $block->escapeHtmlAttr($_option->getId()) ?>]"
            value="<?= $block->escapeHtmlAttr($_selections[0]->getSelectionId()) ?>"/>
        <?php else: ?>
            <select multiple="multiple"
                    size="5"
                    id="bundle-option-<?=
                    $block->escapeHtmlAttr($productId); ?>-<?=
                    $block->escapeHtmlAttr($_option->getId()) ?>"
                    data-option-id="<?=$block->escapeHtmlAttr($_option->getId()) ?>"
                    name="bundle_option[<?=
                    $block->escapeHtmlAttr($productId); ?>][<?=
                    $block->escapeHtmlAttr($_option->getId()) ?>][]"
                    data-selector="bundle_option[<?=
                    $block->escapeHtmlAttr($productId); ?>][<?=
                    $block->escapeHtmlAttr($_option->getId()) ?>][]"
                    class="bundle-option-<?=
                    $block->escapeHtmlAttr($productId); ?>-<?=
                    $block->escapeHtmlAttr($_option->getId())?>
                    multiselect product bundle option change-container-classname"
                    <?php if ($_option->getRequired()) { echo 'data-validate={required:true}'; } ?>>
                <?php if (!$_option->getRequired()): ?>
                    <option value=""><?= $block->escapeHtml(__('None')) ?></option>
                <?php endif; ?>
                <?php foreach ($_selections as $_selection): ?>
                    <option value="<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                    <?php if ($block->isSelected($_selection)) {
                        echo ' selected="selected"';
                    } ?>
                    <?php if (!$_selection->isSaleable()) {
                        echo ' disabled="disabled"';
                    } ?>>
                        <?= /* @noEscape */ $block->getSelectionQtyTitlePrice($_selection, false) ?>
                    </option>
                <?php endforeach; ?>
            </select>
        <?php endif; ?>
    </div>
</div>
