<?php
/**
 * @category  Dinesh FrequentlyBought
 * @package   Dinesh_FrequentlyBought
 * @copyright Copyright (c) 2017 Dinesh
 * @author    Dinesh Team <support@dinesh.com>
 */
$_option = $block->getOption(); ?>
<?php $productId = $block->getProduct()->getId();?>
<?php $_selections  = $_option->getSelections(); ?>
<?php $_default     = $_option->getDefaultSelection(); ?>
<?php list($_defaultQty, $_canChangeQty) = $block->getDefaultValues(); ?>

<div
class="mg-fbt-field-option field option <?=
$block->escapeHtmlAttr(($_option->getRequired()) ? ' required': ''); ?>"
id="mp-fbt-bundle-option-<?=
$block->escapeHtmlAttr($productId); ?>-<?=
$block->escapeHtmlAttr($_option->getId());?>"
data-price-amount="0">
    <label class="label">
        <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="control">
        <div class="nested options-list">
            <?php if ($block->showSingle()): ?>
                <?= /* @noEscape */ $block->getSelectionTitlePrice($_selections[0]) ?>
                <input type="hidden"
                    class="bundle-option-<?=
                    $block->escapeHtmlAttr($productId); ?>-<?=
                    $block->escapeHtmlAttr((int)$_option->getId()) ?>  product bundle option"
                    data-option-id="<?= $block->escapeHtmlAttr($_option->getId()) ?>"
                    name="bundle_option[<?=
                    $block->escapeHtmlAttr($productId); ?>][<?=
                    $block->escapeHtmlAttr((int)$_option->getId()) ?>]"
                    value="<?= $block->escapeHtmlAttr((int)$_selections[0]->getSelectionId()) ?>"
                    id="bundle-option-<?=
                    $block->escapeHtmlAttr($productId); ?>-<?=
                    $block->escapeHtmlAttr((int)$_option->getId()) ?>-<?=
                    $block->escapeHtmlAttr((int)$_selections[0]->getSelectionId()) ?>"
                    checked="checked"
                />
            <?php else:?>
                <?php if (!$_option->getRequired()): ?>
                    <div class="field choice">
                        <input type="radio"
                        class="radio product bundle option"
                        data-option-id="<?= $block->escapeHtmlAttr($_option->getId()) ?>"
                        id="bundle-option-<?=
                        $block->escapeHtmlAttr($productId); ?>-<?=
                        $block->escapeHtmlAttr($_option->getId()) ?>"
                        name="bundle_option[<?=
                        $block->escapeHtmlAttr($productId); ?>][<?=
                        $block->escapeHtmlAttr($_option->getId()) ?>]"
                        data-selector="bundle_option[<?=
                        $block->escapeHtmlAttr($productId); ?>][<?=
                        $block->escapeHtmlAttr($_option->getId()) ?>]"
                        <?= $block->escapeHtml(($_default && $_default->isSalable()) ? '':' checked="checked" '); ?>
                        value=""/>
                        <label
                        class="label"
                        for="bundle-option-<?=
                        $block->escapeHtmlAttr($productId); ?>-<?=
                        $block->escapeHtmlAttr($_option->getId()) ?>">
                            <span><?= $block->escapeHtml(__('None')) ?></span>
                        </label>
                    </div>
                <?php endif; ?>
                <?php foreach ($_selections as $_selection): ?>
                    <div class="field choice">
                        <input type="radio"
                                class="radio product bundle option change-container-classname"
                                data-option-id="<?= $block->escapeHtmlAttr($_option->getId()) ?>"
                                id="bundle-option-<?=
                                $block->escapeHtmlAttr($productId); ?>-<?=
                                $block->escapeHtmlAttr($_option->getId()) ?>-<?=
                                $block->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                                <?php if ($_option->getRequired()) {
                                    echo 'data-validate="{\'validate-one-required-by-name\':true}"';
                                } ?>
                                name="bundle_option[<?=
                                $block->escapeHtmlAttr($productId); ?>][<?=
                                $block->escapeHtmlAttr($_option->getId()) ?>]"
                                data-selector="bundle_option[<?=
                                $block->escapeHtmlAttr($productId); ?>][<?=
                                $block->escapeHtmlAttr($_option->getId()) ?>]"
                                <?php if ($block->isSelected($_selection)) { echo ' checked="checked"'; } ?>
                                <?php if (!$_selection->isSaleable()) { echo ' disabled="disabled"'; } ?>
                                value="<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>"/>
                        <label class="label"
                                for="bundle-option-<?=
                                $block->escapeHtmlAttr($productId); ?>-<?=
                                $block->escapeHtmlAttr($_option->getId()) ?>-<?=
                                $block->escapeHtmlAttr($_selection->getSelectionId()) ?>">
                            <span>
                                <?= /* @noEscape */ $block->getSelectionTitlePrice($_selection) ?>
                            </span>
                        </label>
                    </div>
                <?php endforeach; ?>
                <div id="bundle-option-<?=
                $block->escapeHtmlAttr($productId); ?>-<?=
                $block->escapeHtmlAttr($_option->getId()) ?>-container">
                </div>
            <?php endif; ?>
            <div class="field qty qty-holder">
                <label
                class="label"
                for="bundle-option-<?=
                $block->escapeHtmlAttr($productId); ?>-<?=
                $block->escapeHtmlAttr($_option->getId()) ?>-qty-input">
                    <span><?= $block->escapeHtml(__('Quantity')) ?></span>
                </label>
                <div class="control">
                    <input <?php if (!$_canChangeQty) { echo ' disabled="disabled"'; } ?>
                            id="bundle-option-<?=
                            $block->escapeHtmlAttr($productId); ?>-<?=
                            $block->escapeHtmlAttr($_option->getId())?>-qty-input"
                            class="input-text qty<?php if (!$_canChangeQty) { echo ' qty-disabled'; } ?>"
                            data-option-id="<?= $block->escapeHtmlAttr($_option->getId()) ?>"
                            type="number"
                            name="bundle_option_qty[<?=
                            $block->escapeHtmlAttr($productId); ?>][<?=
                            $block->escapeHtmlAttr($_option->getId()) ?>]"
                            data-selector="bundle_option_qty[<?=
                            $block->escapeHtmlAttr($productId); ?>][<?=
                            $block->escapeHtmlAttr($_option->getId()) ?>]"
                            value="<?= $block->escapeHtmlAttr($_defaultQty) ?>"/>
                </div>
            </div>
        </div>
    </div>
</div>
