<?php
/**
 * @category Mageants HyvaFrequentlyBought
 * @package Mageants_HyvaFrequentlyBought
 * @copyright Copyright (c) 2023 Mageants
 * @author Mageants Team <info@mageants.com>
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\View\BaseImage;
use Magento\Catalog\Pricing\Price\TierPrice;
use Magento\Framework\Escaper;
use Magento\GroupedProduct\Block\Product\View\Type\Grouped;

/**
 * @var BaseImage $block
 * @var Grouped $block
 * @var Escaper $escaper
 */

$block->setPreconfiguredValue();
$product = $block->getProduct();
$associatedProducts = $block->getAssociatedProducts();
$hasAssociatedProducts = count($associatedProducts) > 0;
?>
<script>
    function initGroupedOptions() {
        return {
            isValid: true,
            currentQty: 0,
            price:0,
            totalPrice:0,
            validateForm() {
                const validateInputs = Array.from(
                    document.querySelectorAll('input[name^=super_group]')
                );

                // at least one of the inputs has to have a qty > 0
                this.isValid = validateInputs.filter(
                    input => input.value > 0
                ).length;

                // we set or unset validity for all fields at once
                // and empty string un-sets invalidity
                validateInputs.map(input =>
                    input.setCustomValidity(this.isValid ?
                        "" :
                        "<?= $escaper->escapeJs(__('Please specify the quantity of product(s).')) ?>")
                )
                return true;
            },
            init() {
                const button = document.getElementById('addto-fbt');
                button.addEventListener('click',  (e) => {
                    if (!this.validateForm()) {
                       e.preventDefault();
                    }
                });
            },
            calculatePrice(e){
                this.currentQty = e.value;
                this.totalPrice = 0;
                if(this.currentQty > 0){
                    this.price = parseFloat(this.currentQty) * 
                    parseFloat(e.getAttribute('data-child-product-price-amount'));
                    e.setAttribute('data-child-product-price-total', this.price);
                }else{
                    e.setAttribute('data-child-product-price-total', 0);
                }
                fields = document.querySelectorAll('input[name^=super_group]');
                fields.forEach(element => {
                    this.totalPrice  += 
                    parseFloat(element.getAttribute('data-child-product-price-total'));
                });
                checkboxElement = document.getElementById('mageants-prd-fbt-checkbox-<?= (int)$product->getId() ?>');
                if(checkboxElement){
                    total =this.calculatedFinalPriceWithCustomOptions ||
                    this.calculatedFinalPrice ||
                    this.initialFinalPrice;
                    checkboxElement.setAttribute('data-price-amount', this.totalPrice);
                    window.dispatchEvent(new CustomEvent('update-fbt-total-price',
                    { detail: { totalPrice: this.totalPrice } }));
                }
                window.dispatchEvent(new CustomEvent('update-fbt-price',
                { detail: { newValue: this.totalPrice } }));
            }
        }
    }
</script>
<div x-data="initGroupedOptions()">
<?php if ($hasAssociatedProducts): ?>
    <h2 class="text-gray-900 text-base mb-2">
        <?= $escaper->escapeHtml(__('Grouped product items')) ?>
    </h2>
    <div class="hidden sm:flex py-2 border-t border-gray-300
        w-full items-center justify-between gap-2"
    >
        <div class="text-gray-500 font-semibold text-left">
            <?= $escaper->escapeHtml(__('Product Name')) ?>
        </div>
        <div class="text-gray-500 font-semibold text-left w-20">
            <?= $escaper->escapeHtml(__('Qty')) ?>
        </div>
    </div>

    <?php foreach ($associatedProducts as $item): ?>
        <?php $priceInfo = $item->getPriceInfo()->getPrice('final_price')->getAmount()->getValue(); ?>
        <div class="flex flex-wrap border-t border-gray-300
            py-2 w-full items-center justify-between gap-2"
        >
            <label
                class="text-gray-700 text-left"
                for="super_group[<?= $escaper->escapeHtmlAttr($item->getId()) ?>]"
            >
                <span class="product-item-name font-semibold">
                    <?= $escaper->escapeHtml($item->getName()) ?>
                </span>
                <?php if ($block->getCanShowProductPrice($product)): ?>
                    <?php if ($block->getCanShowProductPrice($item)): ?>
                        <?= /* @noEscape */ $block->getProductPrice($item) ?>
                    <?php endif; ?>
                <?php endif; ?>
            </label>
            <div class="label text-gray-900 text-left sm:text-right w-full sm:w-20">
                <?php if ($product->isSaleable()): ?>

                    <?php if ($item->isSaleable()): ?>
                        <div class="control qty">
                            <input type="number"
                                   min="0"
                                   name="super_group[<?= $escaper->escapeHtmlAttr($product->getId()) ?>][<?= $escaper->escapeHtmlAttr($item->getId()) ?>]" <?php // @codingStandardsIgnoreLine?>
                                   id="super_group[<?= $escaper->escapeHtmlAttr($product->getId()) ?>][<?= $escaper->escapeHtmlAttr($item->getId()) ?>]" <?php // @codingStandardsIgnoreLine?>
                                   value="<?= $escaper->escapeHtmlAttr($item->getQty() * 1) ?>"
                                   title="<?= $escaper->escapeHtmlAttr(__('Qty')) ?>"
                                   form="fbt"
                                   class="qty form-input px-2 py-2 w-20 text-center"
                                   data-child-product-id="<?= $block->escapeHtmlAttr($item->getId()) ?>"
                                   data-child-product-price-amount="<?=
                                    $block->escapeHtmlAttr($priceInfo); ?>"
                                   data-child-product-price-total="0"
                                   :class=" { 'border-red-500 focus:border-red-500 focus:ring-red-500': !isValid }"
                                   @input.debounce="validateForm();calculatePrice($el);"
                            />
                        </div>
                    <?php else: ?>
                        <div class="stock unavailable"
                             title="<?= $escaper->escapeHtmlAttr(__('Availability')) ?>"
                        >
                            <?= $escaper->escapeHtml(__('Out of stock')) ?>
                        </div>
                    <?php endif; ?>

                <?php endif; ?>
            </div>

            <?php if ($block->getCanShowProductPrice($product)
                && $block->getCanShowProductPrice($item)
                && trim($block->getProductPriceHtml(
                    $item,
                    TierPrice::PRICE_CODE
                ))): ?>
                <div class="flex pt-2 w-full items-center">
                    <?= $block->getProductPriceHtml(
                        $item,
                        TierPrice::PRICE_CODE
                    ) ?>
                </div>
            <?php endif; ?>

        </div>
    <?php endforeach; ?>
<?php else: ?>
    <?= $escaper->escapeHtml(__('No options of this product are available.')) ?>
<?php endif; ?>
</div>
